num=10;
num1=0;

try:
    print(10/0)

except:
    print("exception occured")